# postgre
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-frontend-deploy
  labels:
    app: msa-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-frontend
  template:
    metadata:
      name: msa-frontend
      labels:
        app: msa-frontend
    spec:
      containers:
        - name: msa-frontend
          image: yoon741/msa-frontend
          ports:
            - containerPort: 3000 # nodejs이기때문에 3000port
              protocol: TCP
          env:
            - name: USER_SRV_URL
              value: 192.168.56.1:31231  # 임의로 정한 포트 번호 (고정)
            - name: PRODUCT_SRV_URL      #              (서버주소:노드포트)
              value: 192.168.56.1:31232
---
# nodejs
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-usersrv-deploy
  labels:
    app: msa-usesrv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-usersrv
  template:
    metadata:
      name: msa-usersrv
      labels:
        app: msa-usersrv
    spec:
      containers:
        - name: msa-usersrv
          image: yoon741/msa-user-service
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: CORS_ORIGINS
              value: http://192.168.56.1:31230
